export const theme = {
  colors: {
    paper: '#F1ECE1',
    paper2: '#FAF7F0',
    ink: '#2A2521',
    inkSoft: '#7A7166',
    line: '#E2DACB',
    ai: '#3C5366',
    shu: '#B24A2E',
    mizu: '#5B7A8C',
    fuji: '#6E5868',
    matcha: '#6E7850',
    kincha: '#B98A40',
    white: '#FFFFFF',
    transparent: 'transparent',
  },
  fonts: {
    name: 'var(--font-zen-maru)',
    display: 'var(--font-bricolage)',
    body: 'var(--font-hanken)',
    mono: 'var(--font-space-mono)',
  },
  space: {
    1: '4px',
    2: '8px',
    3: '16px',
    4: '24px',
    5: '32px',
    6: '48px',
    7: '64px',
    8: '96px',
    9: '128px',
  },
  radius: {
    sm: '8px',
    md: '14px',
    lg: '22px',
    xl: '32px',
    full: '9999px',
  },
  shadows: {
    sm: '0 2px 10px rgba(42,37,33,0.06)',
    md: '0 6px 22px rgba(42,37,33,0.07)',
    lg: '0 10px 30px rgba(42,37,33,0.12)',
  },
  sizes: {
    frame: '7px',
    navOffset: '14px',
    navMaxWidth: '1120px',
    navToggle: '42px',
    navDropdownOffset: '64px',
    navDropdownRadius: '20px',
    brandDot: '12px',
    sectionPadding: 'clamp(70px, 11vw, 140px)',
    contentMaxWidth: '1120px',
    timelineBreakpoint: '820px',
    timelineMobileGap: '2.4rem',
    timelineHeadMarginBottom: '1.8rem',
    timelineHeadPadding: '0 0.15em',
    timelineHeadUnderlineBottom: '-0.05em',
    timelineHeadUnderlineHeight: '0.15em',
    timelineIndent: '2.2rem',
    timelineLineLeft: '7px',
    timelineLineInset: '8px',
    timelineLineWidth: '3px',
    timelineLineRadius: '3px',
    timelineItemPaddingBottom: '2rem',
    timelineDotTop: '5px',
    timelineDotSize: '17px',
    timelineDotRadius: '5px',
    timelineDotRotate: 'rotate(8deg)',
    timelineDateFont: '0.76rem',
    timelineDatePadding: '0.2rem 0.6rem',
    timelineDateMarginBottom: '0.5rem',
    timelineRoleFont: '19px',
    timelineOrgMargin: '0.1rem 0 0.4rem',
    timelineBodyFont: '0.96rem',
    timelineDescMaxWidth: '42ch',
    timelineBulletFont: '0.9rem',
    timelineBulletLineHeight: '1.55',
    timelineBulletMarginTop: '0.4rem',
    timelineBulletMarginBottom: '0.4rem',
    timelineBulletPaddingLeft: '1.2rem',
    timelineBulletMaxWidth: '44ch',
  },
  border: '1.5px solid #2A2521',
  borderTransparent: '1.5px solid transparent',
} as const;

export type Theme = typeof theme;
